import Head from "next/head";
import Link from "next/link";

export const Home = () => {
  return (
    <div>
      <Head>
        <title>Sylvera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">
          <Link href="/projects/all">Go to all projects</Link>
        </h1>
      </main>
    </div>
  );
};

export default Home;
